// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhoneContacts.Models;

namespace PhoneContacts.Migrations
{
    [DbContext(typeof(ContactContext))]
    [Migration("20210624181332_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PhoneContacts.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            Address = "Ames, IA",
                            Name = "Devin Baack",
                            Note = "Me",
                            PhoneNumber = "712-210-5392"
                        },
                        new
                        {
                            ContactId = 2,
                            Address = "Des Moines, IA",
                            Name = "Bob Sanders",
                            Note = "Coworker",
                            PhoneNumber = "232-430-3392"
                        },
                        new
                        {
                            ContactId = 3,
                            Address = "Ames, IA",
                            Name = "Chuck Jones",
                            Note = "Roommate",
                            PhoneNumber = "332-123-8923"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
